Added user_input.py to test the autocompletion feature for prompt_toolkit
The script must run in terminal, can't run in VSCode as it expect a 'real' terminal.

Error
prompt_toolkit.output.win32.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?